sia_agv:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

tube_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - move_platform_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      move_platform_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10